#!/bin/sh

# bluetooth - systemd suspend/resume hook
#
# Copyright (c) 2020 Andreas Krüger <ak at patientsky.com> and others.
# This software is licensed under the GPL v2 or later.

case $1 in
    pre)  /usr/bin/systemctl stop bluetooth ;;
    post) /usr/bin/systemctl start bluetooth  ;;
esac
